CREATE USER "C##GRUPO1" IDENTIFIED BY "123456"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ENABLE EDITIONS;

-- CUOTA
ALTER USER "C##GRUPO1" QUOTA 102400K ON "USERS"

-- ROLES
GRANT CONNECT TO "C##GRUPO1";
GRANT RESOURCE TO "C##GRUPO1";
GRANT CREATE VIEW TO "C##GRUPO1";


